### ISSUE TITLE
Homepage, Sign In and Sign Up Page

### ISSUE THREAD

**Issue by andela-abankole** [andela/hairven#57]
Base on the mock up, this issue contains view for sign up and sign in and the Homepage

**Comment by andela-ayusuf** [comment]
Point:89  Value: 144

**Comment by andela-ioraelosi** [comment]
Point:34 Value:89

**Comment by andela-sadelokiki** [comment]
point: 55 Value:89

**Comment by andela-batolagbe** [comment]
Point: 21, value 144

**Comment by andela-abankole** [comment]
Point: 55 Value: 55

**Comment by andela-ioraelosi** [comment]
*Point: 34, Value: 89*

**Comment by andela-ioraelosi** [comment]
@andela-batolagbe
