### ISSUE TITLE
Contact hairven team 

### ISSUE THREAD

**Issue by andela-abankole** [andela/hairven#61]
A user should be able to get back to hairven team when he/she has trouble with any part of the web application

**Comment by andela-ioraelosi** [comment]
point: 5 value: 55

**Comment by andela-batolagbe** [comment]
Point: 2, value : 55

**Comment by andela-sadelokiki** [comment]
point: 2, value:21

**Comment by andela-ayusuf** [comment]
Point: 5 Value: 34

**Comment by andela-abankole** [comment]
point: 1 value: 144

**Comment by andela-ioraelosi** [comment]
**Point: 3, Value: 55**

**Comment by andela-ioraelosi** [comment]
@andela-abankole
