### ISSUE TITLE
No CRUD operations can be performed for the `user` resource.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/hairven#7]
It seems that there are no endpoints defined for the `user` resource on the server. We'll need this if we're to have some user-management system.

- [x] Create e2e tests for the `user` resource.
- [x] Create unit tests for the `User` model.
- [x] Implement CRUD for the `user` resource by defining API endpoints.

**Comment by andela-ioraelosi** [comment]
You'll be unable to run tests for this issue unless #6 has been fixed and merged into `staging`.

**Comment by andela-ayusuf** [comment]
Yes, I know. You taught me that :)
