### ISSUE TITLE
Contributor documentation needs to define how issues are handled. 

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/hairven#8]
- [x] Documentation should explain that each issue should be handled by a pair of developers.
- [x] Documentation should explain that a contributor handling an issue should assign the issue to himself/herself. Only one member of the pair need do this.
- [x] Documentation should explain milestones.

**Comment by andela-sadelokiki** [comment]
Jide had more passion for working on this.

**Comment by andela-ioraelosi** [comment]
@andela-sadelokiki No worries. I'll create more issues soon.
